### ISSUE TITLE
Document any LXD setup requirements to run the tutorial

### ISSUE THREAD

**Issue by ChrisMacNaughton** [canonical/microceph#92]

**Comment by mhazan01** [comment]
Hello,

I recently found out about microceph via reddit while looking for a way to test ceph and I just completed the microceph setup on a fresh ubuntu 22.04 running on ESXi VM. Thank you so much for making it so easy.
For the LXD setup part i would suggest to document these points somewhere 

1.  don't forget to turn on hw virtualization if you are running in a vm (duh)
2.  before running the "lxc launch image" cmd, you must run lxd init (you get a warning telling you to do it otherwise), there is a few yes/no and choice options you have to go through, most are default choice but maybe some suggestions are welcome.
3. the default choice for the pool name is "local", might influence the adding storage step

the rest of the setup just goes flawlessly. maybe some future tutorial could include some quick demo for using, crashing and recovering the cluster.

Thanks again for a very useful project !

**Comment by UtkarshBhatthere** [comment]
Closing the issue.
